### ISSUE TITLE
Adding support for @latest

### ISSUE THREAD

**Issue by ayonli** [tani/lib.deno.dev#1]
It would be nice to use `@latest` in the URL to demonstrate that always using the latest version of the package, which is more explicit to human eyes than just omitting the version number.

Great work BTW.

PS: or if you like, I could just submit a PR.

**Comment by tani** [comment]
Thank you for your valuable suggestion. It is indeed an intriguing concept. I have incorporated your idea into the codebase. I kindly request your review and verification of the implemented changes.

**Comment by tani** [comment]
Closed by #3.
